### ISSUE TITLE
Help and questions: PdfGroupTable and PdfTable

### ISSUE THREAD

**Issue by geekabel** [laurentmuller/calculation#22]
I use the PdfTable and PdfGroupTable defined in the project. Except that I have a small problem. I can't reset the default line colour. I used the setGroupStyle but without success. And also on the last line where it says ‘TOTAL TO PAY’. I wanted to merge the first two cells. But I don't really know what to do.

Here's a link to help you see what I mean : https://pastecode.io/s/jwxuj2is
![fiche_construction](https://github.com/user-attachments/assets/3809a680-a053-4d31-95b5-3b750a7b4353)
Here's what my pdf table looks like too

**Comment by laurentmuller** [comment]
Hi,

I think You have to create a separate class for the report.  You must maybe separate the student information and the details to 2 tables.

When You add a row line, You don't need to create a `PdfCell`. Simply pass values to the table as follow:

Before:

```php
$table->addRow(
    new PdfCell('***', 1),
    new PdfCell('***', 1),
    new PdfCell($libelle, 1),
    new PdfCell('', 1),
    new PdfCell($montantBrut, 1)
);
```
After:

```php
$table->addRow(
    '***',
    '***',
    $libelle,
    '',
    $montantBrut
);
```

To add the 'TOTAL TO PAY' on the last line do the follow:

```php
$table->addStyledRow(
    [
        new PdfCell(cols: 2),
        'TOTAL TO PAY',
        '',
        $value
   ],
   PdfStyle::getBoldCellStyle()
);
```

When creating columns for details, set the third column as not fixed. So it will take all the reaming witdh:

```php
$table = PdfGroupTable::instance($pdf);
$table->addColumns(
    PdfColumn::center('N°', 8, true),
    PdfColumn::center('CODE UE', 20, true),
    PdfColumn::left('INTITULÉ', 125),
    PdfColumn::center('CREDIT', 17, true),
    PdfColumn::right('MONTANT', 20, true)
);
```

**Comment by geekabel** [comment]
Thanks for the feedback! On the part that contains the student information, I used cells (`cell` as in the example) instead of tables because not only do I not really know how to do it but I found it much more complicated. 

I would like the rows (lines) to be black like the one above. How do I reset the colour to *black* for the whole thing and not the default?

**Comment by laurentmuller** [comment]
For header style, it's just matter to set style to the header table and group:

```php
$style = PdfStyle::getHeaderStyle()
    ->setFillColor(PdfFillColor::white())
    ->setDrawColor(PdfDrawColor::black());

$table->setGroupStyle($style)
    ->setHeaderStyle($style);
```

For cells, You must create the style and output values:
```php
$style = PdfStyle::getCellStyle()
    ->setDrawColor(PdfDrawColor::black());

$table->startRow($style)
    ->addValues( '***',  '***', $libelle, '', $montantBrut)
    ->endRow();
```

**Comment by geekabel** [comment]
Thanks for the help! this overlay is well done.   One suggestion: I think it would be nice to be able to reset the colour of all the rows when creating a table without necessarily doing it in two steps.

**Comment by laurentmuller** [comment]
I have implemented a default cell style within the `PdfTable` class.

Now, You can use table as follow:

```php
$style = PdfStyle::getCellStyle()
    ->setDrawColor(PdfDrawColor::black());
$table = PdfTable::instance($pdf);
$table->setCellStyle($style);
```

**Comment by geekabel** [comment]
Oh great ! Thanks you !
